language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
env:
    - DJANGO_VERSION=1.4.16
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
    - DJANGO_VERSION=1.7.1
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - python setup.py -q install
script:
    - python messagegroups/tests.py
